namespace WaterRefillingSystem.NewViews
{
    partial class NewCustomerPage
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NewCustomerPage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtCustomerName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtFacebookLink = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtContactNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.rdIsDealer = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtIdNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblErrorMessage = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dtgCustomerItems = new System.Windows.Forms.DataGridView();
            this.btnDeleteCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.dtgCustomerItems)).BeginInit();
            this.SuspendLayout();
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges1;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleBorderRadius = 1;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(15, 30);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 1;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 1;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.BorderRadius = 1;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 1;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(150, 39);
            this.btnSave.TabIndex = 0;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnEdit
            // 
            this.btnEdit.AllowAnimations = true;
            this.btnEdit.AllowMouseEffects = true;
            this.btnEdit.AllowToggling = false;
            this.btnEdit.AnimationSpeed = 200;
            this.btnEdit.AutoGenerateColors = false;
            this.btnEdit.AutoRoundBorders = false;
            this.btnEdit.AutoSizeLeftIcon = true;
            this.btnEdit.AutoSizeRightIcon = true;
            this.btnEdit.BackColor = System.Drawing.Color.Transparent;
            this.btnEdit.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.BackgroundImage")));
            this.btnEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEdit.ButtonText = "Edit";
            this.btnEdit.ButtonTextMarginLeft = 0;
            this.btnEdit.ColorContrastOnClick = 45;
            this.btnEdit.ColorContrastOnHover = 45;
            this.btnEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEdit.CustomizableEdges = borderEdges2;
            this.btnEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnEdit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEdit.ForeColor = System.Drawing.Color.White;
            this.btnEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEdit.IconMarginLeft = 11;
            this.btnEdit.IconPadding = 10;
            this.btnEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEdit.IconSize = 25;
            this.btnEdit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.IdleBorderRadius = 1;
            this.btnEdit.IdleBorderThickness = 1;
            this.btnEdit.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.IdleIconLeftImage = null;
            this.btnEdit.IdleIconRightImage = null;
            this.btnEdit.IndicateFocus = false;
            this.btnEdit.Location = new System.Drawing.Point(171, 30);
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.OnDisabledState.BorderRadius = 1;
            this.btnEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEdit.OnDisabledState.BorderThickness = 1;
            this.btnEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEdit.OnDisabledState.IconLeftImage = null;
            this.btnEdit.OnDisabledState.IconRightImage = null;
            this.btnEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEdit.onHoverState.BorderRadius = 1;
            this.btnEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEdit.onHoverState.BorderThickness = 1;
            this.btnEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.onHoverState.IconLeftImage = null;
            this.btnEdit.onHoverState.IconRightImage = null;
            this.btnEdit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.OnIdleState.BorderRadius = 1;
            this.btnEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEdit.OnIdleState.BorderThickness = 1;
            this.btnEdit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.OnIdleState.IconLeftImage = null;
            this.btnEdit.OnIdleState.IconRightImage = null;
            this.btnEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEdit.OnPressedState.BorderRadius = 1;
            this.btnEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEdit.OnPressedState.BorderThickness = 1;
            this.btnEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.OnPressedState.IconLeftImage = null;
            this.btnEdit.OnPressedState.IconRightImage = null;
            this.btnEdit.Size = new System.Drawing.Size(150, 39);
            this.btnEdit.TabIndex = 1;
            this.btnEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEdit.TextMarginLeft = 0;
            this.btnEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEdit.UseDefaultRadiusAndThickness = true;
            this.btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            // 
            // txtCustomerName
            // 
            this.txtCustomerName.AcceptsReturn = false;
            this.txtCustomerName.AcceptsTab = false;
            this.txtCustomerName.AnimationSpeed = 200;
            this.txtCustomerName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCustomerName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCustomerName.AutoSizeHeight = true;
            this.txtCustomerName.BackColor = System.Drawing.Color.Transparent;
            this.txtCustomerName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCustomerName.BackgroundImage")));
            this.txtCustomerName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCustomerName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCustomerName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCustomerName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCustomerName.BorderRadius = 1;
            this.txtCustomerName.BorderThickness = 1;
            this.txtCustomerName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCustomerName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCustomerName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCustomerName.DefaultText = "";
            this.txtCustomerName.FillColor = System.Drawing.Color.White;
            this.txtCustomerName.HideSelection = true;
            this.txtCustomerName.IconLeft = null;
            this.txtCustomerName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerName.IconPadding = 10;
            this.txtCustomerName.IconRight = null;
            this.txtCustomerName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerName.Lines = new string[0];
            this.txtCustomerName.Location = new System.Drawing.Point(15, 118);
            this.txtCustomerName.MaxLength = 32767;
            this.txtCustomerName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCustomerName.Modified = false;
            this.txtCustomerName.Multiline = false;
            this.txtCustomerName.Name = "txtCustomerName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCustomerName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerName.OnIdleState = stateProperties4;
            this.txtCustomerName.Padding = new System.Windows.Forms.Padding(3);
            this.txtCustomerName.PasswordChar = '\0';
            this.txtCustomerName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCustomerName.PlaceholderText = "Enter text";
            this.txtCustomerName.ReadOnly = false;
            this.txtCustomerName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCustomerName.SelectedText = "";
            this.txtCustomerName.SelectionLength = 0;
            this.txtCustomerName.SelectionStart = 0;
            this.txtCustomerName.ShortcutsEnabled = true;
            this.txtCustomerName.Size = new System.Drawing.Size(236, 39);
            this.txtCustomerName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCustomerName.TabIndex = 3;
            this.txtCustomerName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCustomerName.TextMarginBottom = 0;
            this.txtCustomerName.TextMarginLeft = 3;
            this.txtCustomerName.TextMarginTop = 1;
            this.txtCustomerName.TextPlaceholder = "Enter text";
            this.txtCustomerName.UseSystemPasswordChar = false;
            this.txtCustomerName.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(15, 97);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(87, 15);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "Customer Name";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtFacebookLink
            // 
            this.txtFacebookLink.AcceptsReturn = false;
            this.txtFacebookLink.AcceptsTab = false;
            this.txtFacebookLink.AnimationSpeed = 200;
            this.txtFacebookLink.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFacebookLink.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFacebookLink.AutoSizeHeight = true;
            this.txtFacebookLink.BackColor = System.Drawing.Color.Transparent;
            this.txtFacebookLink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFacebookLink.BackgroundImage")));
            this.txtFacebookLink.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFacebookLink.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFacebookLink.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFacebookLink.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFacebookLink.BorderRadius = 1;
            this.txtFacebookLink.BorderThickness = 1;
            this.txtFacebookLink.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFacebookLink.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFacebookLink.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFacebookLink.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtFacebookLink.DefaultText = "";
            this.txtFacebookLink.FillColor = System.Drawing.Color.White;
            this.txtFacebookLink.HideSelection = true;
            this.txtFacebookLink.IconLeft = null;
            this.txtFacebookLink.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFacebookLink.IconPadding = 10;
            this.txtFacebookLink.IconRight = null;
            this.txtFacebookLink.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFacebookLink.Lines = new string[0];
            this.txtFacebookLink.Location = new System.Drawing.Point(327, 118);
            this.txtFacebookLink.MaxLength = 32767;
            this.txtFacebookLink.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFacebookLink.Modified = false;
            this.txtFacebookLink.Multiline = false;
            this.txtFacebookLink.Name = "txtFacebookLink";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFacebookLink.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFacebookLink.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFacebookLink.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFacebookLink.OnIdleState = stateProperties8;
            this.txtFacebookLink.Padding = new System.Windows.Forms.Padding(3);
            this.txtFacebookLink.PasswordChar = '\0';
            this.txtFacebookLink.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFacebookLink.PlaceholderText = "Enter text";
            this.txtFacebookLink.ReadOnly = false;
            this.txtFacebookLink.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFacebookLink.SelectedText = "";
            this.txtFacebookLink.SelectionLength = 0;
            this.txtFacebookLink.SelectionStart = 0;
            this.txtFacebookLink.ShortcutsEnabled = true;
            this.txtFacebookLink.Size = new System.Drawing.Size(236, 39);
            this.txtFacebookLink.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFacebookLink.TabIndex = 6;
            this.txtFacebookLink.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFacebookLink.TextMarginBottom = 0;
            this.txtFacebookLink.TextMarginLeft = 3;
            this.txtFacebookLink.TextMarginTop = 1;
            this.txtFacebookLink.TextPlaceholder = "Enter text";
            this.txtFacebookLink.UseSystemPasswordChar = false;
            this.txtFacebookLink.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(327, 97);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(76, 15);
            this.bunifuLabel2.TabIndex = 4;
            this.bunifuLabel2.Text = "Facebook Link";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtContactNumber
            // 
            this.txtContactNumber.AcceptsReturn = false;
            this.txtContactNumber.AcceptsTab = false;
            this.txtContactNumber.AnimationSpeed = 200;
            this.txtContactNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtContactNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtContactNumber.AutoSizeHeight = true;
            this.txtContactNumber.BackColor = System.Drawing.Color.Transparent;
            this.txtContactNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtContactNumber.BackgroundImage")));
            this.txtContactNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtContactNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtContactNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtContactNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtContactNumber.BorderRadius = 1;
            this.txtContactNumber.BorderThickness = 1;
            this.txtContactNumber.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtContactNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtContactNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtContactNumber.DefaultText = "";
            this.txtContactNumber.FillColor = System.Drawing.Color.White;
            this.txtContactNumber.HideSelection = true;
            this.txtContactNumber.IconLeft = null;
            this.txtContactNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactNumber.IconPadding = 10;
            this.txtContactNumber.IconRight = null;
            this.txtContactNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactNumber.Lines = new string[0];
            this.txtContactNumber.Location = new System.Drawing.Point(15, 207);
            this.txtContactNumber.MaxLength = 32767;
            this.txtContactNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtContactNumber.Modified = false;
            this.txtContactNumber.Multiline = false;
            this.txtContactNumber.Name = "txtContactNumber";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactNumber.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtContactNumber.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactNumber.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactNumber.OnIdleState = stateProperties12;
            this.txtContactNumber.Padding = new System.Windows.Forms.Padding(3);
            this.txtContactNumber.PasswordChar = '\0';
            this.txtContactNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtContactNumber.PlaceholderText = "Enter text";
            this.txtContactNumber.ReadOnly = false;
            this.txtContactNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtContactNumber.SelectedText = "";
            this.txtContactNumber.SelectionLength = 0;
            this.txtContactNumber.SelectionStart = 0;
            this.txtContactNumber.ShortcutsEnabled = true;
            this.txtContactNumber.Size = new System.Drawing.Size(236, 39);
            this.txtContactNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtContactNumber.TabIndex = 3;
            this.txtContactNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtContactNumber.TextMarginBottom = 0;
            this.txtContactNumber.TextMarginLeft = 3;
            this.txtContactNumber.TextMarginTop = 1;
            this.txtContactNumber.TextPlaceholder = "Enter text";
            this.txtContactNumber.UseSystemPasswordChar = false;
            this.txtContactNumber.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(18, 97);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(87, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Customer Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // rdIsDealer
            // 
            this.rdIsDealer.AllowBindingControlLocation = false;
            this.rdIsDealer.BackColor = System.Drawing.Color.Transparent;
            this.rdIsDealer.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rdIsDealer.BorderThickness = 1;
            this.rdIsDealer.Checked = true;
            this.rdIsDealer.Location = new System.Drawing.Point(329, 297);
            this.rdIsDealer.Name = "rdIsDealer";
            this.rdIsDealer.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rdIsDealer.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdIsDealer.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rdIsDealer.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rdIsDealer.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdIsDealer.Size = new System.Drawing.Size(21, 21);
            this.rdIsDealer.TabIndex = 5;
            this.rdIsDealer.Text = null;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(18, 186);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(89, 15);
            this.bunifuLabel4.TabIndex = 4;
            this.bunifuLabel4.Text = "Contact Number";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtIdNumber
            // 
            this.txtIdNumber.AcceptsReturn = false;
            this.txtIdNumber.AcceptsTab = false;
            this.txtIdNumber.AnimationSpeed = 200;
            this.txtIdNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtIdNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtIdNumber.AutoSizeHeight = true;
            this.txtIdNumber.BackColor = System.Drawing.Color.Transparent;
            this.txtIdNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtIdNumber.BackgroundImage")));
            this.txtIdNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtIdNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtIdNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtIdNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtIdNumber.BorderRadius = 1;
            this.txtIdNumber.BorderThickness = 1;
            this.txtIdNumber.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtIdNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtIdNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtIdNumber.DefaultText = "";
            this.txtIdNumber.Enabled = false;
            this.txtIdNumber.FillColor = System.Drawing.Color.White;
            this.txtIdNumber.HideSelection = true;
            this.txtIdNumber.IconLeft = null;
            this.txtIdNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdNumber.IconPadding = 10;
            this.txtIdNumber.IconRight = null;
            this.txtIdNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdNumber.Lines = new string[0];
            this.txtIdNumber.Location = new System.Drawing.Point(327, 207);
            this.txtIdNumber.MaxLength = 32767;
            this.txtIdNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtIdNumber.Modified = false;
            this.txtIdNumber.Multiline = false;
            this.txtIdNumber.Name = "txtIdNumber";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdNumber.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtIdNumber.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdNumber.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdNumber.OnIdleState = stateProperties16;
            this.txtIdNumber.Padding = new System.Windows.Forms.Padding(3);
            this.txtIdNumber.PasswordChar = '\0';
            this.txtIdNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtIdNumber.PlaceholderText = "Enter text";
            this.txtIdNumber.ReadOnly = false;
            this.txtIdNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtIdNumber.SelectedText = "";
            this.txtIdNumber.SelectionLength = 0;
            this.txtIdNumber.SelectionStart = 0;
            this.txtIdNumber.ShortcutsEnabled = true;
            this.txtIdNumber.Size = new System.Drawing.Size(236, 39);
            this.txtIdNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtIdNumber.TabIndex = 6;
            this.txtIdNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtIdNumber.TextMarginBottom = 0;
            this.txtIdNumber.TextMarginLeft = 3;
            this.txtIdNumber.TextMarginTop = 1;
            this.txtIdNumber.TextPlaceholder = "Enter text";
            this.txtIdNumber.UseSystemPasswordChar = false;
            this.txtIdNumber.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(327, 186);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(58, 15);
            this.bunifuLabel5.TabIndex = 4;
            this.bunifuLabel5.Text = "ID Number";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.AnimationSpeed = 200;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.AutoSizeHeight = true;
            this.txtAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddress.BorderRadius = 1;
            this.txtAddress.BorderThickness = 1;
            this.txtAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.White;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            this.txtAddress.Location = new System.Drawing.Point(17, 288);
            this.txtAddress.MaxLength = 32767;
            this.txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = false;
            this.txtAddress.Name = "txtAddress";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddress.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties20;
            this.txtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "Enter text";
            this.txtAddress.ReadOnly = false;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(236, 39);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddress.TabIndex = 3;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 3;
            this.txtAddress.TextMarginTop = 1;
            this.txtAddress.TextPlaceholder = "Enter text";
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(21, 267);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(42, 15);
            this.bunifuLabel6.TabIndex = 4;
            this.bunifuLabel6.Text = "Address";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblErrorMessage
            // 
            this.lblErrorMessage.AllowParentOverrides = false;
            this.lblErrorMessage.AutoEllipsis = false;
            this.lblErrorMessage.AutoSize = false;
            this.lblErrorMessage.CursorType = null;
            this.lblErrorMessage.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblErrorMessage.Location = new System.Drawing.Point(631, 165);
            this.lblErrorMessage.Name = "lblErrorMessage";
            this.lblErrorMessage.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblErrorMessage.Size = new System.Drawing.Size(137, 81);
            this.lblErrorMessage.TabIndex = 4;
            this.lblErrorMessage.Text = "Error Message";
            this.lblErrorMessage.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblErrorMessage.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblErrorMessage.Visible = false;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(356, 303);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(33, 15);
            this.bunifuLabel8.TabIndex = 4;
            this.bunifuLabel8.Text = "Dealer";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel8.Visible = false;
            // 
            // dtgCustomerItems
            // 
            this.dtgCustomerItems.AllowUserToAddRows = false;
            this.dtgCustomerItems.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dtgCustomerItems.Location = new System.Drawing.Point(21, 364);
            this.dtgCustomerItems.Name = "dtgCustomerItems";
            this.dtgCustomerItems.Size = new System.Drawing.Size(757, 252);
            this.dtgCustomerItems.TabIndex = 7;
            this.dtgCustomerItems.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtgCustomerItems_CellClick);
            // 
            // btnDeleteCustomer
            // 
            this.btnDeleteCustomer.AllowAnimations = true;
            this.btnDeleteCustomer.AllowMouseEffects = true;
            this.btnDeleteCustomer.AllowToggling = false;
            this.btnDeleteCustomer.AnimationSpeed = 200;
            this.btnDeleteCustomer.AutoGenerateColors = false;
            this.btnDeleteCustomer.AutoRoundBorders = false;
            this.btnDeleteCustomer.AutoSizeLeftIcon = true;
            this.btnDeleteCustomer.AutoSizeRightIcon = true;
            this.btnDeleteCustomer.BackColor = System.Drawing.Color.Transparent;
            this.btnDeleteCustomer.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDeleteCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDeleteCustomer.BackgroundImage")));
            this.btnDeleteCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDeleteCustomer.ButtonText = "Delete";
            this.btnDeleteCustomer.ButtonTextMarginLeft = 0;
            this.btnDeleteCustomer.ColorContrastOnClick = 45;
            this.btnDeleteCustomer.ColorContrastOnHover = 45;
            this.btnDeleteCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnDeleteCustomer.CustomizableEdges = borderEdges3;
            this.btnDeleteCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDeleteCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDeleteCustomer.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDeleteCustomer.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDeleteCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDeleteCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDeleteCustomer.IconMarginLeft = 11;
            this.btnDeleteCustomer.IconPadding = 10;
            this.btnDeleteCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDeleteCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDeleteCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDeleteCustomer.IconSize = 25;
            this.btnDeleteCustomer.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDeleteCustomer.IdleBorderRadius = 1;
            this.btnDeleteCustomer.IdleBorderThickness = 1;
            this.btnDeleteCustomer.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDeleteCustomer.IdleIconLeftImage = null;
            this.btnDeleteCustomer.IdleIconRightImage = null;
            this.btnDeleteCustomer.IndicateFocus = false;
            this.btnDeleteCustomer.Location = new System.Drawing.Point(327, 30);
            this.btnDeleteCustomer.Name = "btnDeleteCustomer";
            this.btnDeleteCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteCustomer.OnDisabledState.BorderRadius = 1;
            this.btnDeleteCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDeleteCustomer.OnDisabledState.BorderThickness = 1;
            this.btnDeleteCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteCustomer.OnDisabledState.IconLeftImage = null;
            this.btnDeleteCustomer.OnDisabledState.IconRightImage = null;
            this.btnDeleteCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDeleteCustomer.onHoverState.BorderRadius = 1;
            this.btnDeleteCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDeleteCustomer.onHoverState.BorderThickness = 1;
            this.btnDeleteCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDeleteCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCustomer.onHoverState.IconLeftImage = null;
            this.btnDeleteCustomer.onHoverState.IconRightImage = null;
            this.btnDeleteCustomer.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDeleteCustomer.OnIdleState.BorderRadius = 1;
            this.btnDeleteCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDeleteCustomer.OnIdleState.BorderThickness = 1;
            this.btnDeleteCustomer.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDeleteCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCustomer.OnIdleState.IconLeftImage = null;
            this.btnDeleteCustomer.OnIdleState.IconRightImage = null;
            this.btnDeleteCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDeleteCustomer.OnPressedState.BorderRadius = 1;
            this.btnDeleteCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDeleteCustomer.OnPressedState.BorderThickness = 1;
            this.btnDeleteCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDeleteCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCustomer.OnPressedState.IconLeftImage = null;
            this.btnDeleteCustomer.OnPressedState.IconRightImage = null;
            this.btnDeleteCustomer.Size = new System.Drawing.Size(150, 39);
            this.btnDeleteCustomer.TabIndex = 1;
            this.btnDeleteCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDeleteCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDeleteCustomer.TextMarginLeft = 0;
            this.btnDeleteCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDeleteCustomer.UseDefaultRadiusAndThickness = true;
            this.btnDeleteCustomer.Click += new System.EventHandler(this.btnDeleteCustomer_Click);
            // 
            // NewCustomerPage
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(806, 636);
            this.Controls.Add(this.dtgCustomerItems);
            this.Controls.Add(this.txtIdNumber);
            this.Controls.Add(this.txtFacebookLink);
            this.Controls.Add(this.rdIsDealer);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.lblErrorMessage);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.txtAddress);
            this.Controls.Add(this.txtContactNumber);
            this.Controls.Add(this.txtCustomerName);
            this.Controls.Add(this.btnDeleteCustomer);
            this.Controls.Add(this.btnEdit);
            this.Controls.Add(this.btnSave);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "NewCustomerPage";
            this.Text = "NewCustomerPage";
            this.Load += new System.EventHandler(this.NewCustomerPage_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtgCustomerItems)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDeleteCustomer;

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnEdit;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtFacebookLink;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtContactNumber;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuRadioButton rdIsDealer;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox txtIdNumber;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel lblErrorMessage;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private System.Windows.Forms.DataGridView dtgCustomerItems;
    }
}