namespace WaterRefillingSystem.NewViews
{
    partial class OrderPage
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(OrderPage));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txtCustomerName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCustomerId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCustomerContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtIsDealer = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCustomerAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnAddToCart = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRemove = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cmbItemTitle = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbServiceOption = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbBorrowedGallon = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbOwnGallon = new Bunifu.UI.WinForms.BunifuDropdown();
            this.dtgOrderQueue = new System.Windows.Forms.DataGridView();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.dtgOrderQueue)).BeginInit();
            this.SuspendLayout();
            // 
            // txtCustomerName
            // 
            this.txtCustomerName.AcceptsReturn = false;
            this.txtCustomerName.AcceptsTab = false;
            this.txtCustomerName.AnimationSpeed = 200;
            this.txtCustomerName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCustomerName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCustomerName.AutoSizeHeight = true;
            this.txtCustomerName.BackColor = System.Drawing.Color.Transparent;
            this.txtCustomerName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCustomerName.BackgroundImage")));
            this.txtCustomerName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCustomerName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCustomerName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCustomerName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCustomerName.BorderRadius = 1;
            this.txtCustomerName.BorderThickness = 1;
            this.txtCustomerName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCustomerName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCustomerName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCustomerName.DefaultText = "";
            this.txtCustomerName.Enabled = false;
            this.txtCustomerName.FillColor = System.Drawing.Color.White;
            this.txtCustomerName.HideSelection = true;
            this.txtCustomerName.IconLeft = null;
            this.txtCustomerName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerName.IconPadding = 10;
            this.txtCustomerName.IconRight = null;
            this.txtCustomerName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerName.Lines = new string[0];
            this.txtCustomerName.Location = new System.Drawing.Point(12, 28);
            this.txtCustomerName.MaxLength = 32767;
            this.txtCustomerName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCustomerName.Modified = false;
            this.txtCustomerName.Multiline = false;
            this.txtCustomerName.Name = "txtCustomerName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCustomerName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerName.OnIdleState = stateProperties4;
            this.txtCustomerName.Padding = new System.Windows.Forms.Padding(3);
            this.txtCustomerName.PasswordChar = '\0';
            this.txtCustomerName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCustomerName.PlaceholderText = "Enter text";
            this.txtCustomerName.ReadOnly = false;
            this.txtCustomerName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCustomerName.SelectedText = "";
            this.txtCustomerName.SelectionLength = 0;
            this.txtCustomerName.SelectionStart = 0;
            this.txtCustomerName.ShortcutsEnabled = true;
            this.txtCustomerName.Size = new System.Drawing.Size(260, 39);
            this.txtCustomerName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCustomerName.TabIndex = 0;
            this.txtCustomerName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCustomerName.TextMarginBottom = 0;
            this.txtCustomerName.TextMarginLeft = 3;
            this.txtCustomerName.TextMarginTop = 1;
            this.txtCustomerName.TextPlaceholder = "Enter text";
            this.txtCustomerName.UseSystemPasswordChar = false;
            this.txtCustomerName.WordWrap = true;
            // 
            // txtCustomerId
            // 
            this.txtCustomerId.AcceptsReturn = false;
            this.txtCustomerId.AcceptsTab = false;
            this.txtCustomerId.AnimationSpeed = 200;
            this.txtCustomerId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCustomerId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCustomerId.AutoSizeHeight = true;
            this.txtCustomerId.BackColor = System.Drawing.Color.Transparent;
            this.txtCustomerId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCustomerId.BackgroundImage")));
            this.txtCustomerId.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCustomerId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCustomerId.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCustomerId.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCustomerId.BorderRadius = 1;
            this.txtCustomerId.BorderThickness = 1;
            this.txtCustomerId.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCustomerId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCustomerId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerId.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCustomerId.DefaultText = "";
            this.txtCustomerId.Enabled = false;
            this.txtCustomerId.FillColor = System.Drawing.Color.White;
            this.txtCustomerId.HideSelection = true;
            this.txtCustomerId.IconLeft = null;
            this.txtCustomerId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerId.IconPadding = 10;
            this.txtCustomerId.IconRight = null;
            this.txtCustomerId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerId.Lines = new string[0];
            this.txtCustomerId.Location = new System.Drawing.Point(12, 93);
            this.txtCustomerId.MaxLength = 32767;
            this.txtCustomerId.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCustomerId.Modified = false;
            this.txtCustomerId.Multiline = false;
            this.txtCustomerId.Name = "txtCustomerId";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerId.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCustomerId.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerId.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerId.OnIdleState = stateProperties8;
            this.txtCustomerId.Padding = new System.Windows.Forms.Padding(3);
            this.txtCustomerId.PasswordChar = '\0';
            this.txtCustomerId.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCustomerId.PlaceholderText = "Enter text";
            this.txtCustomerId.ReadOnly = false;
            this.txtCustomerId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCustomerId.SelectedText = "";
            this.txtCustomerId.SelectionLength = 0;
            this.txtCustomerId.SelectionStart = 0;
            this.txtCustomerId.ShortcutsEnabled = true;
            this.txtCustomerId.Size = new System.Drawing.Size(260, 39);
            this.txtCustomerId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCustomerId.TabIndex = 0;
            this.txtCustomerId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCustomerId.TextMarginBottom = 0;
            this.txtCustomerId.TextMarginLeft = 3;
            this.txtCustomerId.TextMarginTop = 1;
            this.txtCustomerId.TextPlaceholder = "Enter text";
            this.txtCustomerId.UseSystemPasswordChar = false;
            this.txtCustomerId.WordWrap = true;
            // 
            // txtCustomerContact
            // 
            this.txtCustomerContact.AcceptsReturn = false;
            this.txtCustomerContact.AcceptsTab = false;
            this.txtCustomerContact.AnimationSpeed = 200;
            this.txtCustomerContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCustomerContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCustomerContact.AutoSizeHeight = true;
            this.txtCustomerContact.BackColor = System.Drawing.Color.Transparent;
            this.txtCustomerContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCustomerContact.BackgroundImage")));
            this.txtCustomerContact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCustomerContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCustomerContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCustomerContact.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCustomerContact.BorderRadius = 1;
            this.txtCustomerContact.BorderThickness = 1;
            this.txtCustomerContact.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCustomerContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCustomerContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerContact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCustomerContact.DefaultText = "";
            this.txtCustomerContact.Enabled = false;
            this.txtCustomerContact.FillColor = System.Drawing.Color.White;
            this.txtCustomerContact.HideSelection = true;
            this.txtCustomerContact.IconLeft = null;
            this.txtCustomerContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerContact.IconPadding = 10;
            this.txtCustomerContact.IconRight = null;
            this.txtCustomerContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerContact.Lines = new string[0];
            this.txtCustomerContact.Location = new System.Drawing.Point(12, 158);
            this.txtCustomerContact.MaxLength = 32767;
            this.txtCustomerContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCustomerContact.Modified = false;
            this.txtCustomerContact.Multiline = false;
            this.txtCustomerContact.Name = "txtCustomerContact";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerContact.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCustomerContact.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerContact.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerContact.OnIdleState = stateProperties12;
            this.txtCustomerContact.Padding = new System.Windows.Forms.Padding(3);
            this.txtCustomerContact.PasswordChar = '\0';
            this.txtCustomerContact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCustomerContact.PlaceholderText = "Enter text";
            this.txtCustomerContact.ReadOnly = false;
            this.txtCustomerContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCustomerContact.SelectedText = "";
            this.txtCustomerContact.SelectionLength = 0;
            this.txtCustomerContact.SelectionStart = 0;
            this.txtCustomerContact.ShortcutsEnabled = true;
            this.txtCustomerContact.Size = new System.Drawing.Size(260, 39);
            this.txtCustomerContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCustomerContact.TabIndex = 0;
            this.txtCustomerContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCustomerContact.TextMarginBottom = 0;
            this.txtCustomerContact.TextMarginLeft = 3;
            this.txtCustomerContact.TextMarginTop = 1;
            this.txtCustomerContact.TextPlaceholder = "Enter text";
            this.txtCustomerContact.UseSystemPasswordChar = false;
            this.txtCustomerContact.WordWrap = true;
            // 
            // txtIsDealer
            // 
            this.txtIsDealer.AcceptsReturn = false;
            this.txtIsDealer.AcceptsTab = false;
            this.txtIsDealer.AnimationSpeed = 200;
            this.txtIsDealer.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtIsDealer.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtIsDealer.AutoSizeHeight = true;
            this.txtIsDealer.BackColor = System.Drawing.Color.Transparent;
            this.txtIsDealer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtIsDealer.BackgroundImage")));
            this.txtIsDealer.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtIsDealer.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtIsDealer.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtIsDealer.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtIsDealer.BorderRadius = 1;
            this.txtIsDealer.BorderThickness = 1;
            this.txtIsDealer.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtIsDealer.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtIsDealer.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIsDealer.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtIsDealer.DefaultText = "";
            this.txtIsDealer.Enabled = false;
            this.txtIsDealer.FillColor = System.Drawing.Color.White;
            this.txtIsDealer.HideSelection = true;
            this.txtIsDealer.IconLeft = null;
            this.txtIsDealer.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIsDealer.IconPadding = 10;
            this.txtIsDealer.IconRight = null;
            this.txtIsDealer.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIsDealer.Lines = new string[0];
            this.txtIsDealer.Location = new System.Drawing.Point(12, 223);
            this.txtIsDealer.MaxLength = 32767;
            this.txtIsDealer.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtIsDealer.Modified = false;
            this.txtIsDealer.Multiline = false;
            this.txtIsDealer.Name = "txtIsDealer";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIsDealer.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtIsDealer.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIsDealer.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIsDealer.OnIdleState = stateProperties16;
            this.txtIsDealer.Padding = new System.Windows.Forms.Padding(3);
            this.txtIsDealer.PasswordChar = '\0';
            this.txtIsDealer.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtIsDealer.PlaceholderText = "Enter text";
            this.txtIsDealer.ReadOnly = false;
            this.txtIsDealer.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtIsDealer.SelectedText = "";
            this.txtIsDealer.SelectionLength = 0;
            this.txtIsDealer.SelectionStart = 0;
            this.txtIsDealer.ShortcutsEnabled = true;
            this.txtIsDealer.Size = new System.Drawing.Size(260, 39);
            this.txtIsDealer.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtIsDealer.TabIndex = 0;
            this.txtIsDealer.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtIsDealer.TextMarginBottom = 0;
            this.txtIsDealer.TextMarginLeft = 3;
            this.txtIsDealer.TextMarginTop = 1;
            this.txtIsDealer.TextPlaceholder = "Enter text";
            this.txtIsDealer.UseSystemPasswordChar = false;
            this.txtIsDealer.WordWrap = true;
            // 
            // txtCustomerAddress
            // 
            this.txtCustomerAddress.AcceptsReturn = false;
            this.txtCustomerAddress.AcceptsTab = false;
            this.txtCustomerAddress.AnimationSpeed = 200;
            this.txtCustomerAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCustomerAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCustomerAddress.AutoSizeHeight = true;
            this.txtCustomerAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtCustomerAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCustomerAddress.BackgroundImage")));
            this.txtCustomerAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCustomerAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCustomerAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCustomerAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCustomerAddress.BorderRadius = 1;
            this.txtCustomerAddress.BorderThickness = 1;
            this.txtCustomerAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCustomerAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCustomerAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCustomerAddress.DefaultText = "";
            this.txtCustomerAddress.Enabled = false;
            this.txtCustomerAddress.FillColor = System.Drawing.Color.White;
            this.txtCustomerAddress.HideSelection = true;
            this.txtCustomerAddress.IconLeft = null;
            this.txtCustomerAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerAddress.IconPadding = 10;
            this.txtCustomerAddress.IconRight = null;
            this.txtCustomerAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerAddress.Lines = new string[0];
            this.txtCustomerAddress.Location = new System.Drawing.Point(12, 289);
            this.txtCustomerAddress.MaxLength = 32767;
            this.txtCustomerAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCustomerAddress.Modified = false;
            this.txtCustomerAddress.Multiline = false;
            this.txtCustomerAddress.Name = "txtCustomerAddress";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerAddress.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCustomerAddress.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerAddress.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerAddress.OnIdleState = stateProperties20;
            this.txtCustomerAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtCustomerAddress.PasswordChar = '\0';
            this.txtCustomerAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCustomerAddress.PlaceholderText = "Enter text";
            this.txtCustomerAddress.ReadOnly = false;
            this.txtCustomerAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCustomerAddress.SelectedText = "";
            this.txtCustomerAddress.SelectionLength = 0;
            this.txtCustomerAddress.SelectionStart = 0;
            this.txtCustomerAddress.ShortcutsEnabled = true;
            this.txtCustomerAddress.Size = new System.Drawing.Size(260, 39);
            this.txtCustomerAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCustomerAddress.TabIndex = 0;
            this.txtCustomerAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCustomerAddress.TextMarginBottom = 0;
            this.txtCustomerAddress.TextMarginLeft = 3;
            this.txtCustomerAddress.TextMarginTop = 1;
            this.txtCustomerAddress.TextPlaceholder = "Enter text";
            this.txtCustomerAddress.UseSystemPasswordChar = false;
            this.txtCustomerAddress.WordWrap = true;
            // 
            // btnAddToCart
            // 
            this.btnAddToCart.AllowAnimations = true;
            this.btnAddToCart.AllowMouseEffects = true;
            this.btnAddToCart.AllowToggling = false;
            this.btnAddToCart.AnimationSpeed = 200;
            this.btnAddToCart.AutoGenerateColors = false;
            this.btnAddToCart.AutoRoundBorders = false;
            this.btnAddToCart.AutoSizeLeftIcon = true;
            this.btnAddToCart.AutoSizeRightIcon = true;
            this.btnAddToCart.BackColor = System.Drawing.Color.Transparent;
            this.btnAddToCart.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAddToCart.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddToCart.BackgroundImage")));
            this.btnAddToCart.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.ButtonText = "Add To Cart";
            this.btnAddToCart.ButtonTextMarginLeft = 0;
            this.btnAddToCart.ColorContrastOnClick = 45;
            this.btnAddToCart.ColorContrastOnHover = 45;
            this.btnAddToCart.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAddToCart.CustomizableEdges = borderEdges1;
            this.btnAddToCart.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddToCart.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddToCart.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAddToCart.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAddToCart.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddToCart.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddToCart.ForeColor = System.Drawing.Color.DimGray;
            this.btnAddToCart.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnAddToCart.IconLeft")));
            this.btnAddToCart.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddToCart.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddToCart.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnAddToCart.IconMarginLeft = 11;
            this.btnAddToCart.IconPadding = 17;
            this.btnAddToCart.IconRight = null;
            this.btnAddToCart.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddToCart.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddToCart.IconRightPadding = new System.Windows.Forms.Padding(15, 3, 7, 3);
            this.btnAddToCart.IconSize = 25;
            this.btnAddToCart.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAddToCart.IdleBorderRadius = 0;
            this.btnAddToCart.IdleBorderThickness = 0;
            this.btnAddToCart.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAddToCart.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAddToCart.IdleIconLeftImage")));
            this.btnAddToCart.IdleIconRightImage = null;
            this.btnAddToCart.IndicateFocus = false;
            this.btnAddToCart.Location = new System.Drawing.Point(576, 12);
            this.btnAddToCart.Name = "btnAddToCart";
            this.btnAddToCart.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddToCart.OnDisabledState.BorderRadius = 1;
            this.btnAddToCart.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.OnDisabledState.BorderThickness = 1;
            this.btnAddToCart.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddToCart.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddToCart.OnDisabledState.IconLeftImage = null;
            this.btnAddToCart.OnDisabledState.IconRightImage = null;
            this.btnAddToCart.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnAddToCart.onHoverState.BorderRadius = 1;
            this.btnAddToCart.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.onHoverState.BorderThickness = 1;
            this.btnAddToCart.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnAddToCart.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(55)))), ((int)(((byte)(255)))));
            this.btnAddToCart.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAddToCart.onHoverState.IconLeftImage")));
            this.btnAddToCart.onHoverState.IconRightImage = null;
            this.btnAddToCart.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnAddToCart.OnIdleState.BorderRadius = 1;
            this.btnAddToCart.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.OnIdleState.BorderThickness = 1;
            this.btnAddToCart.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnAddToCart.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnAddToCart.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAddToCart.OnIdleState.IconLeftImage")));
            this.btnAddToCart.OnIdleState.IconRightImage = null;
            this.btnAddToCart.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnAddToCart.OnPressedState.BorderRadius = 1;
            this.btnAddToCart.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddToCart.OnPressedState.BorderThickness = 1;
            this.btnAddToCart.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnAddToCart.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnAddToCart.OnPressedState.IconLeftImage = null;
            this.btnAddToCart.OnPressedState.IconRightImage = null;
            this.btnAddToCart.Size = new System.Drawing.Size(218, 55);
            this.btnAddToCart.TabIndex = 4;
            this.btnAddToCart.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddToCart.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddToCart.TextMarginLeft = 0;
            this.btnAddToCart.TextPadding = new System.Windows.Forms.Padding(70, 0, 0, 0);
            this.btnAddToCart.UseDefaultRadiusAndThickness = true;
            this.btnAddToCart.Click += new System.EventHandler(this.btnAddToCart_Click);
            // 
            // btnOrder
            // 
            this.btnOrder.AllowAnimations = true;
            this.btnOrder.AllowMouseEffects = true;
            this.btnOrder.AllowToggling = false;
            this.btnOrder.AnimationSpeed = 200;
            this.btnOrder.AutoGenerateColors = false;
            this.btnOrder.AutoRoundBorders = false;
            this.btnOrder.AutoSizeLeftIcon = true;
            this.btnOrder.AutoSizeRightIcon = true;
            this.btnOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnOrder.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.BackgroundImage")));
            this.btnOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.ButtonText = "Order";
            this.btnOrder.ButtonTextMarginLeft = 0;
            this.btnOrder.ColorContrastOnClick = 45;
            this.btnOrder.ColorContrastOnHover = 45;
            this.btnOrder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnOrder.CustomizableEdges = borderEdges2;
            this.btnOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnOrder.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOrder.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOrder.ForeColor = System.Drawing.Color.DimGray;
            this.btnOrder.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnOrder.IconLeft")));
            this.btnOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrder.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnOrder.IconMarginLeft = 11;
            this.btnOrder.IconPadding = 17;
            this.btnOrder.IconRight = null;
            this.btnOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrder.IconRightPadding = new System.Windows.Forms.Padding(15, 3, 7, 3);
            this.btnOrder.IconSize = 25;
            this.btnOrder.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnOrder.IdleBorderRadius = 0;
            this.btnOrder.IdleBorderThickness = 0;
            this.btnOrder.IdleFillColor = System.Drawing.Color.Empty;
            this.btnOrder.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.IdleIconLeftImage")));
            this.btnOrder.IdleIconRightImage = null;
            this.btnOrder.IndicateFocus = false;
            this.btnOrder.Location = new System.Drawing.Point(576, 89);
            this.btnOrder.Name = "btnOrder";
            this.btnOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.OnDisabledState.BorderRadius = 1;
            this.btnOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnDisabledState.BorderThickness = 1;
            this.btnOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.OnDisabledState.IconLeftImage = null;
            this.btnOrder.OnDisabledState.IconRightImage = null;
            this.btnOrder.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnOrder.onHoverState.BorderRadius = 1;
            this.btnOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.onHoverState.BorderThickness = 1;
            this.btnOrder.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnOrder.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(55)))), ((int)(((byte)(255)))));
            this.btnOrder.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.onHoverState.IconLeftImage")));
            this.btnOrder.onHoverState.IconRightImage = null;
            this.btnOrder.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnOrder.OnIdleState.BorderRadius = 1;
            this.btnOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnIdleState.BorderThickness = 1;
            this.btnOrder.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnOrder.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnOrder.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.OnIdleState.IconLeftImage")));
            this.btnOrder.OnIdleState.IconRightImage = null;
            this.btnOrder.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnOrder.OnPressedState.BorderRadius = 1;
            this.btnOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnPressedState.BorderThickness = 1;
            this.btnOrder.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnOrder.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnOrder.OnPressedState.IconLeftImage = null;
            this.btnOrder.OnPressedState.IconRightImage = null;
            this.btnOrder.Size = new System.Drawing.Size(218, 55);
            this.btnOrder.TabIndex = 4;
            this.btnOrder.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrder.TextMarginLeft = 0;
            this.btnOrder.TextPadding = new System.Windows.Forms.Padding(70, 0, 0, 0);
            this.btnOrder.UseDefaultRadiusAndThickness = true;
            this.btnOrder.Click += new System.EventHandler(this.btnOrder_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges3;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.DimGray;
            this.btnCancel.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnCancel.IconLeft")));
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 17;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(15, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleBorderRadius = 0;
            this.btnCancel.IdleBorderThickness = 0;
            this.btnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.IdleIconLeftImage")));
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(576, 167);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 1;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.BorderRadius = 1;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(55)))), ((int)(((byte)(255)))));
            this.btnCancel.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.onHoverState.IconLeftImage")));
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.BorderRadius = 1;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnCancel.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.OnIdleState.IconLeftImage")));
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.BorderRadius = 1;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(218, 55);
            this.btnCancel.TabIndex = 4;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(70, 0, 0, 0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnRemove
            // 
            this.btnRemove.AllowAnimations = true;
            this.btnRemove.AllowMouseEffects = true;
            this.btnRemove.AllowToggling = false;
            this.btnRemove.AnimationSpeed = 200;
            this.btnRemove.AutoGenerateColors = false;
            this.btnRemove.AutoRoundBorders = false;
            this.btnRemove.AutoSizeLeftIcon = true;
            this.btnRemove.AutoSizeRightIcon = true;
            this.btnRemove.BackColor = System.Drawing.Color.Transparent;
            this.btnRemove.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnRemove.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRemove.BackgroundImage")));
            this.btnRemove.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRemove.ButtonText = "Remove";
            this.btnRemove.ButtonTextMarginLeft = 0;
            this.btnRemove.ColorContrastOnClick = 45;
            this.btnRemove.ColorContrastOnHover = 45;
            this.btnRemove.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnRemove.CustomizableEdges = borderEdges4;
            this.btnRemove.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRemove.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRemove.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnRemove.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnRemove.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRemove.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRemove.ForeColor = System.Drawing.Color.DimGray;
            this.btnRemove.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnRemove.IconLeft")));
            this.btnRemove.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRemove.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRemove.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnRemove.IconMarginLeft = 11;
            this.btnRemove.IconPadding = 17;
            this.btnRemove.IconRight = null;
            this.btnRemove.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRemove.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRemove.IconRightPadding = new System.Windows.Forms.Padding(15, 3, 7, 3);
            this.btnRemove.IconSize = 25;
            this.btnRemove.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnRemove.IdleBorderRadius = 0;
            this.btnRemove.IdleBorderThickness = 0;
            this.btnRemove.IdleFillColor = System.Drawing.Color.Empty;
            this.btnRemove.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnRemove.IdleIconLeftImage")));
            this.btnRemove.IdleIconRightImage = null;
            this.btnRemove.IndicateFocus = false;
            this.btnRemove.Location = new System.Drawing.Point(576, 240);
            this.btnRemove.Name = "btnRemove";
            this.btnRemove.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRemove.OnDisabledState.BorderRadius = 1;
            this.btnRemove.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRemove.OnDisabledState.BorderThickness = 1;
            this.btnRemove.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRemove.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRemove.OnDisabledState.IconLeftImage = null;
            this.btnRemove.OnDisabledState.IconRightImage = null;
            this.btnRemove.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnRemove.onHoverState.BorderRadius = 1;
            this.btnRemove.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRemove.onHoverState.BorderThickness = 1;
            this.btnRemove.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnRemove.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(55)))), ((int)(((byte)(255)))));
            this.btnRemove.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnRemove.onHoverState.IconLeftImage")));
            this.btnRemove.onHoverState.IconRightImage = null;
            this.btnRemove.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnRemove.OnIdleState.BorderRadius = 1;
            this.btnRemove.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRemove.OnIdleState.BorderThickness = 1;
            this.btnRemove.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnRemove.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnRemove.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnRemove.OnIdleState.IconLeftImage")));
            this.btnRemove.OnIdleState.IconRightImage = null;
            this.btnRemove.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnRemove.OnPressedState.BorderRadius = 1;
            this.btnRemove.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRemove.OnPressedState.BorderThickness = 1;
            this.btnRemove.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnRemove.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnRemove.OnPressedState.IconLeftImage = null;
            this.btnRemove.OnPressedState.IconRightImage = null;
            this.btnRemove.Size = new System.Drawing.Size(218, 55);
            this.btnRemove.TabIndex = 4;
            this.btnRemove.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRemove.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRemove.TextMarginLeft = 0;
            this.btnRemove.TextPadding = new System.Windows.Forms.Padding(70, 0, 0, 0);
            this.btnRemove.UseDefaultRadiusAndThickness = true;
            // 
            // cmbItemTitle
            // 
            this.cmbItemTitle.BackColor = System.Drawing.Color.Transparent;
            this.cmbItemTitle.BackgroundColor = System.Drawing.Color.White;
            this.cmbItemTitle.BorderColor = System.Drawing.Color.Silver;
            this.cmbItemTitle.BorderRadius = 1;
            this.cmbItemTitle.Color = System.Drawing.Color.Silver;
            this.cmbItemTitle.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbItemTitle.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbItemTitle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbItemTitle.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbItemTitle.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbItemTitle.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbItemTitle.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbItemTitle.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbItemTitle.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbItemTitle.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbItemTitle.FillDropDown = true;
            this.cmbItemTitle.FillIndicator = false;
            this.cmbItemTitle.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbItemTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbItemTitle.ForeColor = System.Drawing.Color.Black;
            this.cmbItemTitle.FormattingEnabled = true;
            this.cmbItemTitle.Icon = null;
            this.cmbItemTitle.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbItemTitle.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbItemTitle.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbItemTitle.IndicatorThickness = 2;
            this.cmbItemTitle.IsDropdownOpened = false;
            this.cmbItemTitle.ItemBackColor = System.Drawing.Color.White;
            this.cmbItemTitle.ItemBorderColor = System.Drawing.Color.White;
            this.cmbItemTitle.ItemForeColor = System.Drawing.Color.Black;
            this.cmbItemTitle.ItemHeight = 26;
            this.cmbItemTitle.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbItemTitle.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbItemTitle.Items.AddRange(new object[] { "Slim Container", "Round Container" });
            this.cmbItemTitle.ItemTopMargin = 3;
            this.cmbItemTitle.Location = new System.Drawing.Point(339, 28);
            this.cmbItemTitle.Name = "cmbItemTitle";
            this.cmbItemTitle.Size = new System.Drawing.Size(194, 32);
            this.cmbItemTitle.TabIndex = 5;
            this.cmbItemTitle.Text = null;
            this.cmbItemTitle.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbItemTitle.TextLeftMargin = 5;
            // 
            // cmbServiceOption
            // 
            this.cmbServiceOption.BackColor = System.Drawing.Color.Transparent;
            this.cmbServiceOption.BackgroundColor = System.Drawing.Color.White;
            this.cmbServiceOption.BorderColor = System.Drawing.Color.Silver;
            this.cmbServiceOption.BorderRadius = 1;
            this.cmbServiceOption.Color = System.Drawing.Color.Silver;
            this.cmbServiceOption.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbServiceOption.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbServiceOption.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbServiceOption.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbServiceOption.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbServiceOption.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbServiceOption.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbServiceOption.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbServiceOption.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbServiceOption.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbServiceOption.FillDropDown = true;
            this.cmbServiceOption.FillIndicator = false;
            this.cmbServiceOption.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbServiceOption.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbServiceOption.ForeColor = System.Drawing.Color.Black;
            this.cmbServiceOption.FormattingEnabled = true;
            this.cmbServiceOption.Icon = null;
            this.cmbServiceOption.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbServiceOption.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbServiceOption.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbServiceOption.IndicatorThickness = 2;
            this.cmbServiceOption.IsDropdownOpened = false;
            this.cmbServiceOption.ItemBackColor = System.Drawing.Color.White;
            this.cmbServiceOption.ItemBorderColor = System.Drawing.Color.White;
            this.cmbServiceOption.ItemForeColor = System.Drawing.Color.Black;
            this.cmbServiceOption.ItemHeight = 26;
            this.cmbServiceOption.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbServiceOption.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbServiceOption.Items.AddRange(new object[] { "Deliver", "Pick-up", "Buy" });
            this.cmbServiceOption.ItemTopMargin = 3;
            this.cmbServiceOption.Location = new System.Drawing.Point(339, 100);
            this.cmbServiceOption.Name = "cmbServiceOption";
            this.cmbServiceOption.Size = new System.Drawing.Size(194, 32);
            this.cmbServiceOption.TabIndex = 5;
            this.cmbServiceOption.Text = null;
            this.cmbServiceOption.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbServiceOption.TextLeftMargin = 5;
            // 
            // cmbBorrowedGallon
            // 
            this.cmbBorrowedGallon.BackColor = System.Drawing.Color.Transparent;
            this.cmbBorrowedGallon.BackgroundColor = System.Drawing.Color.White;
            this.cmbBorrowedGallon.BorderColor = System.Drawing.Color.Silver;
            this.cmbBorrowedGallon.BorderRadius = 1;
            this.cmbBorrowedGallon.Color = System.Drawing.Color.Silver;
            this.cmbBorrowedGallon.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbBorrowedGallon.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbBorrowedGallon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbBorrowedGallon.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbBorrowedGallon.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbBorrowedGallon.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbBorrowedGallon.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbBorrowedGallon.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbBorrowedGallon.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbBorrowedGallon.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbBorrowedGallon.FillDropDown = true;
            this.cmbBorrowedGallon.FillIndicator = false;
            this.cmbBorrowedGallon.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbBorrowedGallon.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbBorrowedGallon.ForeColor = System.Drawing.Color.Black;
            this.cmbBorrowedGallon.FormattingEnabled = true;
            this.cmbBorrowedGallon.Icon = null;
            this.cmbBorrowedGallon.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbBorrowedGallon.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbBorrowedGallon.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbBorrowedGallon.IndicatorThickness = 2;
            this.cmbBorrowedGallon.IsDropdownOpened = false;
            this.cmbBorrowedGallon.ItemBackColor = System.Drawing.Color.White;
            this.cmbBorrowedGallon.ItemBorderColor = System.Drawing.Color.White;
            this.cmbBorrowedGallon.ItemForeColor = System.Drawing.Color.Black;
            this.cmbBorrowedGallon.ItemHeight = 26;
            this.cmbBorrowedGallon.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbBorrowedGallon.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbBorrowedGallon.Items.AddRange(new object[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" });
            this.cmbBorrowedGallon.ItemTopMargin = 3;
            this.cmbBorrowedGallon.Location = new System.Drawing.Point(339, 230);
            this.cmbBorrowedGallon.Name = "cmbBorrowedGallon";
            this.cmbBorrowedGallon.Size = new System.Drawing.Size(194, 32);
            this.cmbBorrowedGallon.TabIndex = 5;
            this.cmbBorrowedGallon.Text = null;
            this.cmbBorrowedGallon.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbBorrowedGallon.TextLeftMargin = 5;
            // 
            // cmbOwnGallon
            // 
            this.cmbOwnGallon.BackColor = System.Drawing.Color.Transparent;
            this.cmbOwnGallon.BackgroundColor = System.Drawing.Color.White;
            this.cmbOwnGallon.BorderColor = System.Drawing.Color.Silver;
            this.cmbOwnGallon.BorderRadius = 1;
            this.cmbOwnGallon.Color = System.Drawing.Color.Silver;
            this.cmbOwnGallon.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbOwnGallon.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbOwnGallon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbOwnGallon.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbOwnGallon.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbOwnGallon.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbOwnGallon.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbOwnGallon.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbOwnGallon.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOwnGallon.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbOwnGallon.FillDropDown = true;
            this.cmbOwnGallon.FillIndicator = false;
            this.cmbOwnGallon.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbOwnGallon.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbOwnGallon.ForeColor = System.Drawing.Color.Black;
            this.cmbOwnGallon.FormattingEnabled = true;
            this.cmbOwnGallon.Icon = null;
            this.cmbOwnGallon.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbOwnGallon.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbOwnGallon.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbOwnGallon.IndicatorThickness = 2;
            this.cmbOwnGallon.IsDropdownOpened = false;
            this.cmbOwnGallon.ItemBackColor = System.Drawing.Color.White;
            this.cmbOwnGallon.ItemBorderColor = System.Drawing.Color.White;
            this.cmbOwnGallon.ItemForeColor = System.Drawing.Color.Black;
            this.cmbOwnGallon.ItemHeight = 26;
            this.cmbOwnGallon.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbOwnGallon.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbOwnGallon.Items.AddRange(new object[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" });
            this.cmbOwnGallon.ItemTopMargin = 3;
            this.cmbOwnGallon.Location = new System.Drawing.Point(339, 165);
            this.cmbOwnGallon.Name = "cmbOwnGallon";
            this.cmbOwnGallon.Size = new System.Drawing.Size(194, 32);
            this.cmbOwnGallon.TabIndex = 5;
            this.cmbOwnGallon.Text = null;
            this.cmbOwnGallon.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbOwnGallon.TextLeftMargin = 5;
            // 
            // dtgOrderQueue
            // 
            this.dtgOrderQueue.AllowUserToAddRows = false;
            this.dtgOrderQueue.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dtgOrderQueue.Location = new System.Drawing.Point(12, 388);
            this.dtgOrderQueue.Name = "dtgOrderQueue";
            this.dtgOrderQueue.Size = new System.Drawing.Size(782, 222);
            this.dtgOrderQueue.TabIndex = 11;
            this.dtgOrderQueue.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtgOrderQueue_CellClick);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 7);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(90, 15);
            this.bunifuLabel1.TabIndex = 12;
            this.bunifuLabel1.Text = "Customer Name:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 77);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(69, 15);
            this.bunifuLabel2.TabIndex = 12;
            this.bunifuLabel2.Text = "Customer ID:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(12, 142);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(100, 15);
            this.bunifuLabel3.TabIndex = 12;
            this.bunifuLabel3.Text = "Customer Contact:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(12, 207);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(47, 15);
            this.bunifuLabel4.TabIndex = 12;
            this.bunifuLabel4.Text = "Is Dealer:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(12, 274);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(100, 15);
            this.bunifuLabel5.TabIndex = 12;
            this.bunifuLabel5.Text = "Customer Address:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(339, 12);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(56, 15);
            this.bunifuLabel6.TabIndex = 12;
            this.bunifuLabel6.Text = "Item Type:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(339, 77);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(80, 15);
            this.bunifuLabel7.TabIndex = 12;
            this.bunifuLabel7.Text = "Service Option:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(339, 144);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(65, 15);
            this.bunifuLabel8.TabIndex = 12;
            this.bunifuLabel8.Text = "Own Gallon:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(339, 207);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(88, 15);
            this.bunifuLabel9.TabIndex = 12;
            this.bunifuLabel9.Text = "Borrowed Gallon";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // OrderPage
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(806, 636);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.dtgOrderQueue);
            this.Controls.Add(this.cmbOwnGallon);
            this.Controls.Add(this.cmbBorrowedGallon);
            this.Controls.Add(this.cmbServiceOption);
            this.Controls.Add(this.cmbItemTitle);
            this.Controls.Add(this.btnRemove);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOrder);
            this.Controls.Add(this.btnAddToCart);
            this.Controls.Add(this.txtCustomerAddress);
            this.Controls.Add(this.txtIsDealer);
            this.Controls.Add(this.txtCustomerContact);
            this.Controls.Add(this.txtCustomerId);
            this.Controls.Add(this.txtCustomerName);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "OrderPage";
            this.Text = "OrderPage";
            this.Load += new System.EventHandler(this.OrderPage_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtgOrderQueue)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerName;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerId;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerContact;
        private Bunifu.UI.WinForms.BunifuTextBox txtIsDealer;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerAddress;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddToCart;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOrder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRemove;
        private Bunifu.UI.WinForms.BunifuDropdown cmbItemTitle;
        private Bunifu.UI.WinForms.BunifuDropdown cmbServiceOption;
        private Bunifu.UI.WinForms.BunifuDropdown cmbBorrowedGallon;
        private Bunifu.UI.WinForms.BunifuDropdown cmbOwnGallon;
        private System.Windows.Forms.DataGridView dtgOrderQueue;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
    }
}